### ISSUE TITLE
script to get quantitative results

### ISSUE THREAD

**Issue by void721** [Letian2003/C-VQA#3]
Thanks for your solid work!

I notice that you only provide infer scripts in path/scripts and save response/new response to csv, do you have any scripts for resulting inference results and get quantitative results?

Thank you for your reply.

**Comment by DTennant** [comment]
Hi, Thanks for your interest in our work.
We will provide the scripts for evaluation ASAP.

**Comment by DTennant** [comment]
Hi, the code for getting quantitative results has been released
